gbadev-org/awesome-gbadev

- README.md
Unsure exactly how to categories all these, but they're good resources and definitely worth including one way or another.
> Added new tutorials / articles / libraries

- README.md
ZigGBA is a work in progress SDK for creating GBA games in Ziglang.
> Add ZigGBA

- README.md
zlib licensed devkitARM alternative by me
> Add gba-toolchain

- README.md
* Added:
* HeartLib, GBAdv, Krawall, Pimpmobile
* Krom's stuff
* "Historical Links" subsection with HAM Mirror and Headspin's Guide
* Updated descriptions for
* devkitARM, Natu, Maxmod, Goodboy Advance
> Various additions & tweaks

- README.md
Hi, I saw this list of resources, and thought that people learning about GBA dev might benefit from reading the popular Pokemon Ruby decompilation.
Also, I happen to have developed a GBA game. It's fairly polished, with fluid animation and digital sound, and includes working code for multiplayer data transfer in SIO multi mode.
> Add Pokeruby decompilation to readme, add BlindJump open source homebrew game

- README.md
Hi! Did this the other day but apparently somehow the PR never got made. :upside_down_face:
> Add Apex Audio System & agbabi, remove dead link to Mirror-HAM

- README.md
The current invite link expired, but this one should work.
> Updated README.MD with new gbadev Discord invite link

- README.md
Also fixed the branding change.
> Removed WIP from gba-plusplus

- README.md
Adding the Tigermoth to Homebrews
> Adding Tigermoth

- README.md
GBA Jam 2021 and GBA Winter Jam '21 links added.
I also have added a missing entry to the table of contents.
> Jams links

- README.md
> Add OpenLara homebrew

- README.md
GBA Dlang is a WIP SDK for GBA development using D, using LLVM toolchain. provides fully functional TONC, GBFS, Maxmod.
> add GBA Dlang

- README.md
I've been working on a set of tests lately to research timing (and other) edge-cases and verify that they are emulated correctly. 
This is aimed mostly towards developers with already advanced emulators.
> Link to NanoBoyAdvance's hardware tests

- README.md
* Add a link to the forums
* Update description of gbadev.org and gbatemp
* Replace the "gba-tools" irc channel with "gbajam"
* Add link to gbajam22
> Add a link to the forums + other tweaks

- README.md
Wasn't sure about the ordering
> Update libseven link, add sdk-seven & meson-gba

- README.md
> Add TinyGo

- README.md
No worries if you want to decline this pull request. 
But, it would be super cool to be listed here.
> Add SkyEmu to the Emulators List

- README.md
- Recently moved to its own github organisation, update links and description
- Add reference to Discord channel
> update sdk-seven info

- README.md
Let me know if this needs changes!
> Adding gba-link-connection to the Libraries list

- README.md
Looks like the structure of the website got completely overhauled
> Fixed dead gamasutra link

- README.md
> Usenti added

- README.md
Hi, thought I'd suggest the addition of this tool I found for picking out colours on the GBA as it helped me. I'm not the maintainer, but I have used it.
> Add BGR555 color picker tool
